import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/modules/shared/components/Navbar";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import { ToastContainer } from "react-toastify";
import Provider from "@/shared/utils/Provider";

const inter = Inter({ subsets: ["latin"] });
interface ToastProviderProps {
  children: React.ReactNode;
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
        
          <Provider>
          <Navbar />
          {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
